AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for oppgave1-sam

Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 bucket for storing images"
    Default: "pgr301-couch-explorers"
  Kandidatnummer:
    Type: String
    Description: "Kandidatnummer for path i S3 bucket"
    Default: "47"
  FunctionName:
    Type: String
    Description: "The name of the lambda function for generating images"
    Default: "47-oppgave1-image-generation-couchx"


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
      LogGroupName: "/aws/lambda/${FunctionName}"  # Specify log group
      ApplicationLogLevel: "INFO"


Resources:
  ImageGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: image_generator/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          KANDIDATNUMMER: !Ref Kandidatnummer
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "bedrock:InvokeModel"
            Resource: "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-image-generator-v1"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
#            Resource: "arn:aws:s3:::pgr301-couch-explorers/47/*"
            Resource: !Sub "arn:aws:s3:::${BucketName}/${Kandidatnummer}/*"


Outputs:
  ImageGenerationApi:
    Description: API Gateway endpoint URL for image generation
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ImageGenerationFunction:
    Description: Image generation Lambda Function ARN
    Value: !GetAtt ImageGenerationFunction.Arn
  ImageGenerationFunctionIamRole:
    Description: IAM Role for the Image Generation Lambda Function
    Value: !GetAtt ImageGenerationFunctionRole.Arn
