name: Deploy Lambda with SAM

on:
  push:
    branches:
      - main  # Specify which branch to run the action on, or modify as per your needs

jobs:
  run-aws-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: eu-west-1  # Specify your region, update if needed

      - name: Run AWS CLI command
        run: |
          sam build --template-file oppgave1-SAM/template.yaml --use-container
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file oppgave1-SAM/samconfig.toml