name: Oppgave 3 - Build and publish Docker image

on:
  push:
    branches:
      - main

jobs:
  BuildAndDeployOppgave3:
    name: Build and publish Java Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker image tags
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        env:
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}}
        run: |
          docker login -u $username -p $password

      - name: Build the Docker image
        run: |
          docker build oppgave3_java_sqs_client/ \
            -f oppgave3_java_sqs_client/Dockerfile \
            -t ${{ secrets.DOCKERHUBUSERNAME }}/oppgave3_java_sqs_client:${{ env.IMAGE_TAG }} \
            -t ${{ secrets.DOCKERHUBUSERNAME }}/oppgave3_java_sqs_client:latest

      - name: Push the Docker images
        run: |
          docker push ${{ secrets.DOCKERHUBUSERNAME }}/oppgave3_java_sqs_client:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUBUSERNAME }}/oppgave3_java_sqs_client:latest
